fixtures:  
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    cron_core:
      repo: "https://github.com/puppetlabs/puppetlabs-cron_core"
      puppet_version: ">= 6.0.0"
